window_padding_width 4

confirm_os_window_close 0

background_opacity 0.9

map ctrl+shift+t new_window
map ctrl+shift+w close_window
map ctrl+shift+up    move_window up
map ctrl+shift+down  move_window down
map ctrl+shift+left  move_window left
map ctrl+shift+right move_window right
map ctrl+shift+pageup   prev_window
map ctrl+shift+pagedown next_window

mouse_double_click_threshold 5
scrollback_lines 5000
initial_window_width  1000
initial_window_height 600

enable_audio_bell no

# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
font_size        12
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Nord
include current-theme.conf
# END_KITTY_THEME
