# Catppuccin Mocha — theme variables
# Used by theme-picker.sh via envsubst

export BG="#1e1e2e"
export BG1="#181825"
export FG="#cdd6f4"
export FG_BRIGHT="#cdd6f4"
export FG_DIM="#6c7086"
export SEP_COLOR="#45475a"
export ACCENT="#cba6f7"
export ACCENT_FG="#1e1e2e"
export BORDER_ACTIVE="#cba6f7"
export BORDER_INACTIVE="#585b70"
export GTK_THEME="Adwaita:dark"
export ALACRITTY_SLUG="catppuccin-mocha"
export NVIM_CS="catppuccin"
export WS_ACTIVE_BG="#313244"
export WS_ACTIVE_FG="#cba6f7"
export WS_ACTIVE_BORDER="#cba6f7"
export URGENT="#f38ba8"
export URGENT_TEXT="#1e1e2e"
export TRAY_BG="#181825"
export TRAY_BORDER="#a6e3a1"
export WB_SEPARATOR="#89b4fa"
export UPDATES_OK="#a6e3a1"
export UPDATES_AVAIL="#f38ba8"
export WINDOW_BORDER="#89dceb"
export MAKO_BORDER_LOW="#a6e3a1"
export MAKO_BORDER_NORMAL="#89b4fa"
export MAKO_BORDER_HIGH="#f38ba8"
export MAKO_BG_HIGH="#313244"
