# ── Window Rules ──────────────────────────────────────────────────────────────
for_window [app_id="org.gnome.Calculator"] floating enable
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="bluetooth"] floating enable
for_window [app_id="pulsemixer"] floating enable
for_window [app_id="kitty"] opacity 0.97
for_window [app_id="yazi"] opacity 0.95
for_window [app_id="screensaver"] fullscreen enable, border none
