ignore-empty-password
show-failed-attempts
daemonize

color=1e1e2e
bs-hl-color=f38ba8
key-hl-color=c4a7e7
ring-color=403d52
ring-ver-color=c4a7e7
ring-wrong-color=f38ba8
inside-color=1e1e2e
inside-ver-color=1e1e2e
inside-wrong-color=1e1e2e
line-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
text-color=cdd6f4
text-ver-color=cdd6f4
text-wrong-color=f38ba8
separator-color=00000000

clock
timestr=%H:%M
datestr=%A, %d %B
