#!/bin/bash
# setup-multimonitor.sh — Interactive multi-monitor setup
# Assigns workspaces 1-3 to primary, 4-10 to secondary.
# Writes workspace rules to monitors.conf and a kanshi profile.

set -uo pipefail

source "$(dirname "$0")/common_functions.sh"

MONITORS_CONF="$HOME/.config/hypr/monitors.conf"
KANSHI_CONF="$HOME/.config/kanshi/config"

echo -e "${GREEN}=== Multi-Monitor Setup ===${NC}"
echo "Workspaces: Primary → 1-3 | Secondary → 4-10"
echo ""

# ── Detect available monitors ────────────────────────────────────────────────
declare -a DETECTED=()

if command -v hyprctl &>/dev/null && [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
    # Inside Hyprland session — use hyprctl
    while IFS= read -r line; do
        DETECTED+=("$line")
    done < <(hyprctl monitors -j 2>/dev/null \
        | python3 -c "import json,sys; m=json.load(sys.stdin); [print(x['name']) for x in m]" \
        2>/dev/null)
fi

# Fallback: scan /sys/class/drm for connected outputs
if [ ${#DETECTED[@]} -eq 0 ]; then
    while IFS= read -r drm_connector; do
        status=$(cat "$drm_connector/status" 2>/dev/null)
        if [ "$status" = "connected" ]; then
            name=$(basename "$drm_connector")
            # Convert kernel name (card1-HDMI-A-1) to Hyprland name (HDMI-A-1)
            name="${name#card*-}"
            DETECTED+=("$name")
        fi
    done < <(find /sys/class/drm -name "card?-*" -type d 2>/dev/null | sort)
fi

if [ ${#DETECTED[@]} -eq 0 ]; then
    echo -e "${YELLOW}Could not detect monitors automatically.${NC}"
    echo "Enter monitor names manually (from 'hyprctl monitors' or xrandr)."
    echo ""
    echo -e "${YELLOW}Primary monitor name (e.g. eDP-1):${NC}"
    read -r PRIMARY
    echo -e "${YELLOW}Secondary monitor name (leave blank if none):${NC}"
    read -r SECONDARY
else
    echo "Detected monitors:"
    for i in "${!DETECTED[@]}"; do
        echo "  $((i+1))) ${DETECTED[$i]}"
    done
    echo ""

    if [ ${#DETECTED[@]} -eq 1 ]; then
        PRIMARY="${DETECTED[0]}"
        SECONDARY=""
        echo -e "${GREEN}Single monitor: $PRIMARY (workspaces 1-10)${NC}"
    else
        echo -e "${YELLOW}Select PRIMARY monitor number (workspaces 1-3):${NC}"
        read -r pri_sel
        while ! [[ "$pri_sel" =~ ^[0-9]+$ ]] || \
              [ "$pri_sel" -lt 1 ] || [ "$pri_sel" -gt "${#DETECTED[@]}" ]; do
            echo -e "${YELLOW}Enter a number between 1 and ${#DETECTED[@]}:${NC}"
            read -r pri_sel
        done
        PRIMARY="${DETECTED[$((pri_sel-1))]}"

        echo ""
        echo -e "${YELLOW}Select SECONDARY monitor (workspaces 4-10), or 0 for none:${NC}"
        read -r sec_sel
        if [[ "$sec_sel" =~ ^[0-9]+$ ]] && [ "$sec_sel" -gt 0 ] && \
           [ "$sec_sel" -le "${#DETECTED[@]}" ] && [ "$sec_sel" -ne "$pri_sel" ]; then
            SECONDARY="${DETECTED[$((sec_sel-1))]}"
        else
            SECONDARY=""
        fi
    fi
fi

echo ""
echo -e "${GREEN}Primary: $PRIMARY${NC}"
[ -n "$SECONDARY" ] && echo -e "${GREEN}Secondary: $SECONDARY${NC}"

# ── Write monitors.conf ──────────────────────────────────────────────────────
echo ""
echo "Writing monitors.conf..."
mkdir -p "$(dirname "$MONITORS_CONF")"

{
    echo "# Monitor Configuration"
    echo "# Generated by setup-multimonitor.sh"
    echo ""
    echo "# Auto-configure all connected monitors"
    echo "monitor = $PRIMARY, preferred, 0x0, 1"
    if [ -n "$SECONDARY" ]; then
        echo "monitor = $SECONDARY, preferred, auto, 1"
    fi
    echo "monitor = , preferred, auto, 1"
    echo ""
    echo "# Workspace assignments"
    echo "workspace = 1, monitor:$PRIMARY, default:true"
    echo "workspace = 2, monitor:$PRIMARY"
    echo "workspace = 3, monitor:$PRIMARY"
    if [ -n "$SECONDARY" ]; then
        echo "workspace = 4, monitor:$SECONDARY, default:true"
        echo "workspace = 5, monitor:$SECONDARY"
        echo "workspace = 6, monitor:$SECONDARY"
        echo "workspace = 7, monitor:$SECONDARY"
        echo "workspace = 8, monitor:$SECONDARY"
        echo "workspace = 9, monitor:$SECONDARY"
        echo "workspace = 10, monitor:$SECONDARY"
    else
        echo "workspace = 4, monitor:$PRIMARY"
        echo "workspace = 5, monitor:$PRIMARY"
        echo "workspace = 6, monitor:$PRIMARY"
        echo "workspace = 7, monitor:$PRIMARY"
        echo "workspace = 8, monitor:$PRIMARY"
        echo "workspace = 9, monitor:$PRIMARY"
        echo "workspace = 10, monitor:$PRIMARY"
    fi
} > "$MONITORS_CONF"

echo -e "${GREEN}Written: $MONITORS_CONF${NC}"

# ── Write kanshi profile ─────────────────────────────────────────────────────
echo ""
echo "Writing kanshi config..."
mkdir -p "$(dirname "$KANSHI_CONF")"

{
    echo "# kanshi multi-monitor profiles"
    echo "# Generated by setup-multimonitor.sh"
    echo "#"
    echo "# Run 'hyprctl monitors' to get resolution/refresh info"
    echo ""
    echo "# Standalone (laptop lid open or desktop)"
    echo "profile standalone {"
    echo "    output $PRIMARY enable"
    echo "}"
    if [ -n "$SECONDARY" ]; then
        echo ""
        echo "# Docked (both monitors connected)"
        echo "profile docked {"
        echo "    output $PRIMARY enable"
        echo "    output $SECONDARY enable"
        echo "}"
        echo ""
        echo "# External only (laptop lid closed)"
        echo "profile external {"
        echo "    output $PRIMARY disable"
        echo "    output $SECONDARY enable"
        echo "}"
    fi
} > "$KANSHI_CONF"

echo -e "${GREEN}Written: $KANSHI_CONF${NC}"

# ── Reload if inside Hyprland ────────────────────────────────────────────────
if command -v hyprctl &>/dev/null && [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
    echo ""
    echo "Reloading Hyprland config..."
    hyprctl reload && echo -e "${GREEN}Reloaded.${NC}" || echo -e "${YELLOW}Reload failed — restart Hyprland manually.${NC}"
fi

echo ""
echo -e "${GREEN}=== Multi-monitor setup complete ===${NC}"
echo ""
echo "Keybindings for workspaces:"
echo "  SUPER+1-3  → Primary monitor workspaces"
[ -n "$SECONDARY" ] && echo "  SUPER+4-0  → Secondary monitor workspaces"
echo ""
echo "Re-run this script anytime you change your monitor setup."
