#!/bin/bash
# setup-multimonitor.sh — Configure Sway multi-monitor workspaces
# - Detects connected monitors via swaymsg
# - Creates kanshi profiles for different configurations
# - Generates workspaces.conf with monitor-specific workspace assignments

set -uo pipefail

source "$(dirname "$0")/common_functions.sh"

KANSHI_CONF="$HOME/.config/kanshi/config"
SWAY_WORKSPACES="$HOME/.config/sway/workspaces.conf"

echo -e "${GREEN}=== Sway Multi-Monitor Setup ===${NC}"
echo "Configure workspace layout across multiple monitors."
echo ""

# --- DETECT MONITORS ---
echo "Detecting monitors..."
declare -a MONITORS=()

if command -v swaymsg &>/dev/null && swaymsg -t get_outputs &>/dev/null; then
    while IFS= read -r monitor_json; do
        if [ -n "$monitor_json" ]; then
            # Parse JSON to extract name (assumes jq is available, fallback to grep)
            if command -v jq &>/dev/null; then
                name=$(echo "$monitor_json" | jq -r '.name' 2>/dev/null)
            else
                # Fallback: extract from JSON without jq
                name=$(echo "$monitor_json" | grep -o '"name":"[^"]*' | cut -d'"' -f4)
            fi
            if [ -n "$name" ] && [ "$name" != "null" ]; then
                MONITORS+=("$name")
            fi
        fi
    done < <(swaymsg -t get_outputs 2>/dev/null | grep -o '{[^}]*"name"[^}]*}')
fi

if [ ${#MONITORS[@]} -eq 0 ]; then
    echo -e "${YELLOW}Could not auto-detect monitors.${NC}"
    echo "Falling back to manual entry..."
    echo ""
    echo -e "${YELLOW}Enter monitor name for primary (e.g., eDP-1, HDMI-A-1):${NC}"
    read -r PRIMARY
    echo -e "${YELLOW}Enter monitor name for secondary (or press Enter to skip):${NC}"
    read -r SECONDARY
    MONITORS=("$PRIMARY")
    [ -n "$SECONDARY" ] && MONITORS+=("$SECONDARY")
else
    echo "Detected monitors:"
    for i in "${!MONITORS[@]}"; do
        echo "  $((i+1))) ${MONITORS[$i]}"
    done
    echo ""

    if [ ${#MONITORS[@]} -eq 1 ]; then
        PRIMARY="${MONITORS[0]}"
        SECONDARY=""
        echo -e "${GREEN}Single monitor detected: $PRIMARY${NC}"
    else
        echo -e "${YELLOW}Select primary monitor (default is 1):${NC}"
        read -rp "Choice (1-${#MONITORS[@]}): " primary_choice
        primary_choice=${primary_choice:-1}

        if ! [[ "$primary_choice" =~ ^[0-9]+$ ]] || ((primary_choice < 1 || primary_choice > ${#MONITORS[@]})); then
            primary_choice=1
        fi
        PRIMARY="${MONITORS[$((primary_choice - 1))]}"

        echo ""
        echo -e "${YELLOW}Select secondary monitor (or press Enter to skip):${NC}"
        read -rp "Choice (1-${#MONITORS[@]}, or Enter): " secondary_choice

        SECONDARY=""
        if [[ "$secondary_choice" =~ ^[0-9]+$ ]] && ((secondary_choice >= 1 && secondary_choice <= ${#MONITORS[@]})); then
            SECONDARY="${MONITORS[$((secondary_choice - 1))]}"
        fi
    fi
fi

echo ""
echo -e "${GREEN}Configuration:${NC}"
echo "  Primary:   $PRIMARY"
echo "  Secondary: ${SECONDARY:-(none)}"
echo ""

# --- CREATE WORKSPACES.CONF ---
echo "Generating workspaces configuration..."
mkdir -p "$HOME/.config/sway"

if [ -z "$SECONDARY" ]; then
    # Single monitor: all workspaces on primary
    cat > "$SWAY_WORKSPACES" << EOF
# Sway workspace assignments
# Generated by setup-multimonitor.sh

# Single monitor configuration
workspace 1 output $PRIMARY
workspace 2 output $PRIMARY
workspace 3 output $PRIMARY
workspace 4 output $PRIMARY
workspace 5 output $PRIMARY
workspace 6 output $PRIMARY
workspace 7 output $PRIMARY
workspace 8 output $PRIMARY
workspace 9 output $PRIMARY
workspace 10 output $PRIMARY
EOF
else
    # Multi-monitor: 1-5 on primary, 6-10 on secondary
    cat > "$SWAY_WORKSPACES" << EOF
# Sway workspace assignments
# Generated by setup-multimonitor.sh

# Multi-monitor configuration
# Primary monitor: workspaces 1-5
workspace 1 output $PRIMARY
workspace 2 output $PRIMARY
workspace 3 output $PRIMARY
workspace 4 output $PRIMARY
workspace 5 output $PRIMARY

# Secondary monitor: workspaces 6-10
workspace 6 output $SECONDARY
workspace 7 output $SECONDARY
workspace 8 output $SECONDARY
workspace 9 output $SECONDARY
workspace 10 output $SECONDARY
EOF
fi

echo -e "${GREEN}Created: $SWAY_WORKSPACES${NC}"

# --- CREATE KANSHI PROFILES ---
echo ""
echo "Generating kanshi profiles..."
mkdir -p "$HOME/.config/kanshi"

cat > "$KANSHI_CONF" << EOF
# kanshi multi-monitor configuration
# Profiles are matched in order; first match is used.
# https://wayland.emersion.fr/kanshi/
#
# Get monitor names:  swaymsg -t get_outputs | grep '"name"'
# Get resolutions:    swaymsg -t get_outputs (look for "current_mode")

# Default: enable all connected outputs
profile {
    output * enable
}
EOF

echo -e "${GREEN}Created: $KANSHI_CONF${NC}"
echo "  (default profile: enable all connected monitors)"

# --- SUMMARY & INSTRUCTIONS ---
echo ""
echo -e "${GREEN}=== Configuration Complete ===${NC}"
echo ""
echo "Workspace layout:"
if [ -z "$SECONDARY" ]; then
    echo "  • All workspaces (1-10) on $PRIMARY"
else
    echo "  • Primary ($PRIMARY):   workspaces 1-5"
    echo "  • Secondary ($SECONDARY): workspaces 6-10"
fi
echo ""
echo "Files created:"
echo "  • $SWAY_WORKSPACES — workspace assignments"
echo "  • $KANSHI_CONF — monitor profiles"
echo ""
echo "Next steps:"
echo "  1. Edit kanshi profiles in: $KANSHI_CONF"
echo "     Example for docked setup:"
echo "       profile docked {"
echo "         output eDP-1 enable resolution 1920x1080 position 0,1440"
echo "         output HDMI-A-1 enable resolution 2560x1440 position 0,0"
echo "       }"
echo "  2. Reload Sway config: swaymsg reload"
echo "  3. Kanshi will apply profiles automatically on monitor changes"
echo ""
echo "Manual monitor control:"
echo "  • List monitors:  swaymsg -t get_outputs"
echo "  • Enable monitor: swaymsg output HDMI-A-1 enable"
echo "  • Set resolution: swaymsg output HDMI-A-1 resolution 2560x1440"
echo "  • Set position:   swaymsg output HDMI-A-1 position 0,0"
