# Window Rules
# https://wiki.hyprland.org/Configuring/Window-Rules/

windowrule {
    name = float-calculator
    match:class = ^(org.gnome.Calculator)$
    float = true
}

windowrule {
    name = float-disks
    match:class = ^(org.gnome.DiskUtility)$
    float = true
}

windowrule {
    name = float-pavucontrol
    match:class = ^(pavucontrol)$
    float = true
}

windowrule {
    name = float-bluetooth
    match:class = ^(Blueman-manager)$
    float = true
}

windowrule {
    name = opacity-terminal
    match:class = ^(Alacritty)$
    opacity = 0.90 0.90
}

windowrule {
    name = opacity-files
    match:class = ^(org.gnome.Nautilus)$
    opacity = 0.95 0.95
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}
